QRCodeReaderコンポーネントの実装
symbol-blockchain-community/symbol-wallet-base pull request #2
Opened 2024-03-22 14:03 UTC by oe-trader

`expo-camera/next` を使ってQRリーダーコンポーネントを実装しました。

- カメラ切り替えとライトON.OFFも実装済み
- アイコンを追加しています
- i18n対応済み(コンポーネント部分だけ)

### 既知の問題
- 初回起動時にカメラのパーミッションを拒否った後、設定アプリでカメラを許可したら以後Expo goごと落ちる
    - 実機のiPhone SE2か3のiOS17.3.1で発生

2024-03-23 23:48 UTC, ymuichiro requested changes
@oe-trader 2点だけコメント加えました〜
他はスムーズに良い感じに動いてました！

2024-03-23 23:48 UTC, ymuichiro commented on components/molecules/QRCodeReader.tsx
> +            <View className={cn('w-11/12 max-w-5xl my-4 h-screen h-5/6 rounded-lg')} />
細かいですがここ `h-screen h-5/6` で同一プロパティの重複見つけました

2024-03-23 23:48 UTC, ymuichiro commented on app.json
Android の実機で試したところ、権限の要求に失敗（一度も権限が要求されずカメラが表示されない）しました。
調べたところ、 app.json に android は以下の行を追加する必要があるみたいです。

```json
{
  "expo": {
    "name": "symbol-wallet-base",
    "slug": "symbol-wallet-base",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "scheme": "symbol-wallet-base",
    "plugins": [
      "expo-secure-store",
      "expo-router",
      "expo-localization",
      [
        "expo-camera",
        {
          "cameraPermission": "Allow $(PRODUCT_NAME) to access your camera",
          "microphonePermission": "Allow $(PRODUCT_NAME) to access your microphone",
          "recordAudioAndroid": true
        }
      ]
    ],
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
+      "permissions": [
+        "android.permission.CAMERA"
+      ]
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

2024-03-23 23:49 UTC, ymuichiro commented on app.json
参考

https://docs.expo.dev/versions/latest/config/app/#permissions

2024-03-24 07:36 UTC, oe-trader commented on components/molecules/QRCodeReader.tsx
> +            <View className={cn('w-11/12 max-w-5xl my-4 h-screen h-5/6 rounded-lg')} />
`h-screen` を消しました！

2024-03-24 07:36 UTC, oe-trader commented on app.json
ありがとうございます！追記しました！

2024-03-24 08:02 UTC, ymuichiro approved these changes

2024-03-24 08:03 UTC, ymuichiro commented
@oe-trader 
ありがとうございます〜 approve しました！

2024-03-24 08:03 UTC, merged