AddressService.tsをSDK v3.2.2に対応
symbol-blockchain-community/symbol-wallet-base pull request #8
Opened 2024-06-04 14:27 UTC by oe-trader

タイトルの通り。

検証用のコードは以下
```ts
import { AddressService } from "../AddressService";

const ADDRESS = "TC4XUBLC4ZR3LVARL6HW3BX4WH7I6BSHPQSDW6Y";
const ENCODED_ADDRESS = "98B97A0562E663B5D4115F8F6D86FCB1FE8F06477C243B7B";
const PUBLIC_KEY =
    "710F14C683EDF04507A8EF7AD5FE51047FFFB9E23F66FC96FF210C1AEF6B895B";
const PAYLOAD = `B00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000019854410A000000000000000B572CB40B00000098B97A0562E663B5D4115F8F6D86FCB1FE8F06477C243B7B0000010000000000CE8BA0672E21C0720000000000000000`;

(async () => {
    try {
        // TEST1: isValid()
        const isValid = AddressService.isValidAddress(ADDRESS, "testnet");
        console.log(`Test1: ${isValid ? "OK" : "NG"}`);

        // TEST2: createFromPublicKey()
        const test2: AddressService = AddressService.createFromPublicKey(
            PUBLIC_KEY,
            "testnet"
        );
        console.log(`Test2: ${test2.plain() === ADDRESS ? "OK" : "NG"}`);

        // TEST3: createFromRawAddress()
        const test3: AddressService =
            AddressService.createFromRawAddress(ADDRESS);
        console.log(`Test3: ${test3.plain() === ADDRESS ? "OK" : "NG"}`);

        // TEST4: createFromEncoded()
        const test4: AddressService =
            AddressService.createFromEncoded(ENCODED_ADDRESS);
        console.log(`Test4: ${test4.plain() === ADDRESS ? "OK" : "NG"}`);

        // TEST5: payloadToAddress()
        const test5: string = AddressService.payloadToAddress(PAYLOAD);
        console.log(`Test5: ${test5 === ADDRESS ? "OK" : "NG"}`);

        console.log("All tests passed!!");
    } catch (e) {
        console.error(e);
    }
})();

```

2024-06-04 14:29 UTC, oe-trader commented on services/AddressService.ts
>        return encodedAddress;
ここだけAddressServiceではなく文字列のアドレスを返しているが問題ないか？

2024-06-04 14:29 UTC, oe-trader commented on services/AddressService.ts
> +    const address = new SymbolFacade(networkType).network.publicKeyToAddress(new PublicKey(publicKey));
facadeのインスタンスは毎回生成してよいか？
NetworkTypeも毎回引数で取得する？

2024-06-05 22:19 UTC, ymuichiro commented on services/AddressService.ts
>        return encodedAddress;
@oe-trader 

試してみたところ、このメソッドは最新の sdk ではいらなくなりそうですね。次のように試したところ、 uint8 array も受け取ってくれるようになったので、消しちゃって良さそうです。

```ts
import { Address, SymbolFacade } from "symbol-sdk/symbol";
import { utils } from "symbol-sdk";

const uint8: Uint8Array = utils.hexToUint8(
  "68A6E353886A1DF1DD66B5C370C0E4DCFC2F58306968AC78"
);
const address = new Address(uint8);

const plain = address.toString();
const pretty = plain.match(/.{1,5}/g)?.join("-");

console.log({ pretty, plain });

// {
//   pretty: 'NCTOG-U4INI-O7DXL-GWXBX-BQHE3-T6C6W-BQNFU-KY6A',
//   plain: 'NCTOGU4INIO7DXLGWXBXBQHE3T6C6WBQNFUKY6A'
// }
```

2024-06-05 22:21 UTC, ymuichiro commented on services/AddressService.ts
> +    const address = new SymbolFacade(networkType).network.publicKeyToAddress(new PublicKey(publicKey));
これは address の生成パターンが networkType ごとに異なるので、これで良いかなと思いました。
別パターンもありますが、これも networkType が必要ですし。

const facade = new SymbolFacade("testnet");
facade.createPublicAccount({} as any).address;

2024-06-06 00:21 UTC, ymuichiro requested changes
@oe-trader 

確認しました。一箇所のみ指摘入れています。
アドレス検証周りは私も手元で試してみたのですが、ネットワーク種別でも検証してくれるのが便利ですね。

```ts
import { Address, SymbolFacade } from "symbol-sdk/symbol";
import { utils } from "symbol-sdk";

const hexAddress: string = "68A6E353886A1DF1DD66B5C370C0E4DCFC2F58306968AC78";

const uint8: Uint8Array = utils.hexToUint8(hexAddress);
const address = new Address(uint8);

const plain = address.toString();
const pretty = plain.match(/.{1,5}/g)?.join("-") as string;

console.log({ pretty, plain });

// {
//   pretty: 'NCTOG-U4INI-O7DXL-GWXBX-BQHE3-T6C6W-BQNFU-KY6A',
//   plain: 'NCTOGU4INIO7DXLGWXBXBQHE3T6C6WBQNFUKY6A'
// }

const facade = new SymbolFacade("mainnet");

console.log(facade.network.isValidAddress(address)); // true 注意: アドレスがネットワークに属しているかも検証される。つまり networkType 相違は false
console.log(facade.network.isValidAddressString(plain)); // true
console.log(facade.network.isValidAddressString(pretty)); // false
console.log(facade.network.isValidAddressString(hexAddress)); // false
```

2024-06-07 06:21 UTC, ymuichiro approved these changes
@oe-trader commit を1つ追加しました。approve します！

2024-06-07 06:22 UTC, merged